spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: newuser
    password: A1234

  jpa:
    hibernate:
      ddl-auto: update   #OR validate
    show-sql: true

server:
  port: 8080


  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: none
